version: '3.8'

services:
  nginx-likelion:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - likelion-backend

  likelion-backend:
    image: likelion-backend:latest
    deploy:
      replicas: 2
#    ports:
#      - "9082:8082"